defaults:
  - dataset: indian_pines
  - model: grnet_quantum
  - _self_

hydra:
  run:
    dir: runs/${now:%Y-%m-%d_%H-%M-%S}

# General Training Config
epochs: 50
lr: 0.01
seed: 42
device: "cuda"

# Validation
debug: false
